# Generated by Django 2.2.14 on 2020-08-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('co2_rate', models.PositiveIntegerField(verbose_name='co2_rate')),
            ],
            options={
                'abstract': False,
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionInterpolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('co2_rate', models.PositiveIntegerField(verbose_name='co2_rate')),
            ],
            options={
                'abstract': False,
                'ordering': ['datetime'],
            },
        ),
    ]
