# Generated by Django 2.2.14 on 2020-08-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2_consumption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('winter', 'winter'), ('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn')], max_length=6, verbose_name='name')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
